[package]
name = "abci2"
version = "0.1.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.8.1"
integer-encoding = "1.0.7"

[build-dependencies]
protobuf-codegen-pure = "2.8.1"

[[bin]]
name = "simple-example"
path = "./examples/simple.rs"
