[package]
name = "abci2"
description = "Low-level ABCI protocol server"
version = "0.1.3-alpha.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
log = "0.4.17"
tendermint-proto = "0.23.7"
prost = "0.10.4"
thiserror = "1.0.31"

[[example]]
name = "simple"
path = "./examples/simple.rs"
