[package]
name = "abci2"
description = "Low-level ABCI protocol server"
version = "0.1.3-alpha.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
protobuf = "=2.10.1"
failure = "0.1.6"
log = "0.4.8"

[[example]]
name = "simple"
path = "./examples/simple.rs"
